# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab17333e32029c2cde8c43d3205c21adc6647f788395355ab13cf6ab1d6806313d86cb5c2195f3d028e9ca7eb720fd5251cb1121be52d54294dadf00a6a41ccf

test:
  secret_key_base: 0e393e3f1ffeaab1e3f1fdbe9077d5b39af0b61084c8900b123cafc45edbb9e64d45d0cdd501c257dcd925d9a911be2a18d2471b8498fc024fd9cf025d28a752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
